feat(docs): Update README docs
SoftboxLab/gandalf-lint-node pull request #1
Opened 2019-10-23 16:57 UTC by mkny

Update's the project README.md

2019-10-23 22:02 UTC, stanleygomes submitted a review, later dismissed

2019-10-25 14:48 UTC, vilaboim requested changes

2019-10-25 14:48 UTC, vilaboim commented on README.md
> +![npm](https://img.shields.io/npm/v/@softboxlab/eslint-config-gandalf-lint-react)
This badge is related to gandalf-lint-react :thinking:

2019-10-25 14:48 UTC, vilaboim commented on README.md
> +  Bad NodeJS Code Shall Not Pass
```suggestion
  Bad Node.js Code Shall Not Pass
```

2019-10-30 18:08 UTC, vilaboim approved these changes

2019-11-01 00:06 UTC, fredericofigueira approved these changes

2019-11-02 22:00 UTC, stanleygomes approved these changes

2019-11-03 12:21 UTC, merged